name: Automation Test

on:
  repository_dispatch:
    types: do-something

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install chrome
      run: |
        sudo apt-get update 
        sudo apt-get install google-chrome-stable 
    - name: Install package
      run: |
        npm install
    - name: Get latest build
      uses: ./actions/get_latest_build
      with:
        branch: SSR-473
    - name: Install latest build kintone-ui-component
      run: |
        npm install ${{steps.get_latest_build.outputs.files}}
    - name: Preparation source
      run: |
        domain=${{secrets.DOMAIN}} appID=${{secrets.APPID}} username=${{secrets.USERNAME}} password=${{secrets.PASSWORD}} test=${{secrets.TEST_JS}} npm run preparation
    - name: Run test
      run: |
        domain=${{secrets.DOMAIN}} appID=${{secrets.APPID}} username=${{secrets.USERNAME}} password=${{secrets.PASSWORD}} test=${{secrets.TEST_JS}} npm run test
      env:
        CI: true
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
